version: "2"
run:
  concurrency: 3
  issues-exit-code: 1
  tests: true
linters:
  default: all
  # This list of linters is not a recommendation (same thing for all this configuration file).
  # We intentionally use a limited set of linters.
  # See the comment on top of this file.
  disable:
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - err113
    - exhaustruct
    - forcetypeassert
    - intrange
    - inamedparam
    - ireturn
    - mnd
    - nilnil
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - tagalign
    - tagliatelle
    - testifylint
    - thelper
    - varnamelen
    - wsl
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/tj/assert
              desc: not allowed, did you mean testify assert?
            - pkg: reflect
              desc: please don't use reflect package
            - pkg: github.com/gofrs/uuid
              desc: please use github.com/google/uuid
    dupl:
      threshold: 175
    errcheck:
      check-type-assertions: false
    funlen:
      lines: 80
      statements: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - regexpMust
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 128
    gocyclo:
      min-complexity: 18
    godox:
      keywords:
        - HACK
        - OPTIMIZE
        - TODO
        - BUG
    lll:
      line-length: 200
      tab-width: 2
    misspell:
      locale: UK
      extra-words:
        - typo: authorised
          correction: authorized
        - typo: authorisation
          correction: authorization
      ignore-rules:
        - color
        - center
        - centers
        - initializes
        - organization
        - liter
        - milliliter
        - unauthorized
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: var-naming
          arguments:
            - - ID
            - []
          severity: warning
          disabled: false
        - name: argument-limit
          severity: warning
          disabled: true
        - name: banned-characters
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: file-header
          disabled: true
        - name: cognitive-complexity
          arguments:
            - 15
          disabled: false
        - name: unused-receiver
          disabled: true
        - name: function-length
          arguments:
            - 30
            - 0
          disabled: false
        - name: line-length-limit
          disabled: true
        - name: cyclomatic
          arguments:
            - 7
          disabled: false
        - name: function-result-limit
          arguments:
            - 4
          severity: warning
          disabled: false
        - name: import-alias-naming
          arguments:
            - ^[a-z][a-z0-9A-Z]{0,}$
          severity: warning
          disabled: false
        - name: use-errors-new
          disabled: true
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - revive
        path: migrations\.go
      - linters:
          - gocritic
          - mnd
        path: _mock\.go
      - linters:
          - dupl
        path: postgres/.*\.go
      - linters:
          - dupl
          - err113
          - errcheck
          - funlen
          - gocritic
          - gocyclo
          - gosec
          - maintidx
          - musttag
          - revive
          - testpackage
          - unused
          - lll
          - dupword
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: pkg/metrics
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - lll
        text: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
severity:
  default: error
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/wimspaargaren/gql-gen-mcp)
    gofmt:
      simplify: true
  exclusions:
    generated: disable
    paths:
      - third_party$
      - builtin$
      - examples$
